# POSTTEST 7

Dimas sasongko_2009106093
## TensorFlow

## > Import Package ------------------------------------------------------------------------------------------------------------

In [32]:
import tensorflow as tf
import numpy as np

### > Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor

In [33]:
tf_Random = tf.random.normal([5, 5], mean=0, stddev=1, seed=1).numpy()

### > Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor

In [34]:
tf_Prima = tf.constant([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 71, 73, 79, 83, 89, 97, 101], shape=[5, 5], dtype=tf.float32)

### > Tampilkan dimensi dari kedua variable tersebut

In [35]:
tf_Random

array([[ 0.02631566,  0.59973025,  2.1930096 ,  0.70548636, -0.15317097],
       [-0.87380695, -0.41602153,  0.10885387, -0.30898607, -0.08477694],
       [-1.4043791 ,  0.3359162 , -0.5440277 , -0.6701393 , -1.1809127 ],
       [-1.1672325 ,  1.168095  , -0.6827249 ,  1.2158072 ,  0.6584982 ],
       [ 0.20425868,  0.07945652,  0.07206825, -0.4303542 , -0.32767358]],
      dtype=float32)

tf_Prima

### > Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)

1. Aritmatika pertambahan (add)

In [36]:
print("Hasil pertambahan :",tf.add(tf_Random,tf_Prima).numpy())

Hasil pertambahan : [[  2.0263157   3.5997303   7.1930094   7.7054863  10.846829 ]
 [ 12.126193   16.583979   19.108854   22.691013   28.915222 ]
 [ 29.595621   37.335915   40.45597    42.32986    45.819088 ]
 [ 51.832767   60.168095   60.317276   72.215805   73.6585   ]
 [ 79.20426    83.07946    89.07207    96.56965   100.672325 ]]


2. Aritmatika pengurangan (subtract)

In [37]:
print("Hasil pengurangan :",tf.subtract(tf_Random, tf_Prima).numpy())

Hasil pengurangan : [[  -1.9736843   -2.4002697   -2.8069904   -6.2945137  -11.153171 ]
 [ -13.873807   -17.416021   -18.891146   -23.308987   -29.084778 ]
 [ -32.40438    -36.664085   -41.54403    -43.67014    -48.180912 ]
 [ -54.167233   -57.831905   -61.682724   -69.784195   -72.3415   ]
 [ -78.79574    -82.92054    -88.92793    -97.43035   -101.327675 ]]


3. Aritmatika perkalian (multiply)

In [38]:
print("hasil perkalian :",tf.multiply(tf_Random, tf_Prima).numpy())

hasil perkalian : [[ 5.2631319e-02  1.7991908e+00  1.0965048e+01  4.9384046e+00
  -1.6848807e+00]
 [-1.1359490e+01 -7.0723658e+00  2.0682235e+00 -7.1066794e+00
  -2.4585311e+00]
 [-4.3535751e+01  1.2428899e+01 -2.2305136e+01 -2.8815990e+01
  -5.5502899e+01]
 [-6.1863323e+01  6.8917603e+01 -4.1646217e+01  8.6322311e+01
   4.8070370e+01]
 [ 1.6136436e+01  6.5948915e+00  6.4140744e+00 -4.1744358e+01
  -3.3095032e+01]]


4. Aritmatika pembagian (divide)

In [39]:
print("hasil pembagian =",tf.divide (tf_Random, tf_Prima).numpy())

hasil pembagian = [[ 0.01315783  0.19991009  0.4386019   0.10078377 -0.01392463]
 [-0.06721592 -0.02447185  0.00572915 -0.01343418 -0.00292334]
 [-0.04530255  0.00907882 -0.01326897 -0.01558464 -0.0251258 ]
 [-0.02202326  0.01979822 -0.01119221  0.01712405  0.00902052]
 [ 0.00258555  0.00095731  0.00080976 -0.00443664 -0.00324429]]


5. Aritmatika logaritma (math.log)

In [40]:
print("hasil logaritma math.log =", tf.math.log (tf_Random, tf_Prima).numpy())

hasil logaritma math.log = [[-3.6375911  -0.5112753   0.78527486 -0.34886786         nan]
 [        nan         nan -2.2177489          nan         nan]
 [        nan -1.0908935          nan         nan         nan]
 [        nan  0.15537421         nan  0.19540821 -0.41779348]
 [-1.588368   -2.5325453  -2.6301417          nan         nan]]


##### > Tampilkan nilai maksimal dan minimal dari variable random_tensor

Nilai Maksimal

In [41]:
print("Nilai Maksimal :", tf.argmax(tf_Random, axis=0).numpy())

Nilai Maksimal : [4 3 0 3 3]


Nilai Minimal

In [42]:
print("Nilai Minimal :",tf.argmin(tf_Random, axis=0).numpy())

Nilai Minimal : [2 1 3 2 2]


### > Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [43]:
tf_Random = tf.random.normal([5,5], mean=0, stddev=1, seed=1)
tf_Prima = tf.constant([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 71, 73, 79, 83, 89, 97, 101], shape=[5, 5], dtype=tf.float32)
print("size original data:",tf_Random.shape,tf_Prima.shape)
concated_tensor = tf.concat([tf_Random,tf_Prima],axis=0)
print("size concatenated data:",concated_tensor.shape)

size original data: (5, 5) (5, 5)
size concatenated data: (10, 5)


### > Tampilkan hasil sorting dari kedua variable di atas. (descending)

In [48]:
print("existing Random tensor data:",tf_Random.numpy())
sorted_random = tf.sort(tf_Random, direction = "DESCENDING")
print("random tensor sorted by descending order:",sorted_random.numpy())

existing Random tensor data: [[-0.09829053  1.2328393   1.0841055  -0.03147423  0.8239386 ]
 [-1.343977   -0.5825029  -1.2442445   0.78904885 -1.5128906 ]
 [ 2.1204236   0.8943947  -0.08512403 -3.0256145   0.0541295 ]
 [ 0.4327671  -0.29732513  0.9791035   1.6596949   0.11454969]
 [ 0.01530319 -0.2602644  -0.7217767  -0.8932251   0.35070774]]
random tensor sorted by descending order: [[ 1.2328393   1.0841055   0.8239386  -0.03147423 -0.09829053]
 [ 0.78904885 -0.5825029  -1.2442445  -1.343977   -1.5128906 ]
 [ 2.1204236   0.8943947   0.0541295  -0.08512403 -3.0256145 ]
 [ 1.6596949   0.9791035   0.4327671   0.11454969 -0.29732513]
 [ 0.35070774  0.01530319 -0.2602644  -0.7217767  -0.8932251 ]]


In [47]:
print("existing prime tensor data:",tf_Prima.numpy())
sorted_prime = tf.sort(tf_Prima, direction = "DESCENDING")
print("prime tensor sorted by descending order:",sorted_prime.numpy())

existing prime tensor data: [[  2.   3.   5.   7.  11.]
 [ 13.  17.  19.  23.  29.]
 [ 31.  37.  41.  43.  47.]
 [ 53.  59.  61.  71.  73.]
 [ 79.  83.  89.  97. 101.]]
prime tensor sorted by descending order: [[ 11.   7.   5.   3.   2.]
 [ 29.  23.  19.  17.  13.]
 [ 47.  43.  41.  37.  31.]
 [ 73.  71.  61.  59.  53.]
 [101.  97.  89.  83.  79.]]


# ----------------------------------------------END--------------------------------------------------------